version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - npm install @openzeppelin/contracts
      - npm install dotenv
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npm install @openzeppelin/contracts
      - npm install dotenv
      - npx truffle test
stages:
  - pipeline:
      jobs:
        - compile
        - test